### ISSUE TITLE
这个不是我之前翻译的文档?

### ISSUE THREAD

**Issue by halois** [logicshan/logicshan.github.io#1]

**Comment by logicshan** [comment]
是的. 之前学谱序列的时候发现的. 我自己复制了一份, 放到我项目下面了.
但仅是学习. 不声明任何所有权.(我应该没有改动任何东西). 如有冒犯, 请见谅.

**Comment by halois** [comment]
哈~没有了. 我突然发现你这里有一份中文的介绍, 想下载看看, 结果看到是我之前无聊时翻译的, 实际上我也是私自翻译的~
可以留一个你的联系方式吗? 看到你有很多笔记很感兴趣

**Comment by logicshan** [comment]
@halois 我加了你 K-理论 讨论班的微信群. coconut=nut 就是我. 你导师是不是唐国平? 如果是的话, 你的一个师兄现在在我们学校. 我汕头大学.
